FROM python:3.10-slim

# Устанавливаем Google Chrome и зависимости для него
RUN apt-get update && apt-get install -y \
    wget gnupg unzip curl \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update && apt-get install -y google-chrome-stable

# Копируем наш проект в контейнер
WORKDIR /app
COPY . .

# Устанавливаем библиотеки
RUN pip install --no-cache-dir -r requirements.txt

# Команда для запуска тестов при старте контейнера
CMD ["pytest", "--alluredir=allure-results"]
